spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_HOST:172.17.0.2}:5432/investment
    username: ${POSTGRESQL_USERNAME:postgres}
    password: ${POSTGRESQL_PASSWORD:admin}
    hikari:
      connection-timeout: 5000
      idle-timeout: 10000
      minimum-idle: 1
      maximum-pool-size: 3
      connection-test-query: SELECT 1
  jpa:
    open-in-view: false
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
  mvc.problemdetails.enabled: true

management.endpoints.web.exposure.include: "*"

server:
  port: ${SERVER_PORT:8080}
  error:
    include-binding-errors: always
    include-message: always

logging.level.com.hss.investment: DEBUG

investments.kaggle:
  username: ${KAGGLE_USER}
  key: ${KAGGLE_KEY}
