apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresql.fullname" . }}-initdb
data:
  create-database.sql: |
    {{- range .Values.postgresql.extraDatabases }}
    CREATE DATABASE {{ . | quote }};
    {{- end }}