apiVersion: v2
name: bank
description: Bank Helm.
version: 1.0.0
appVersion: 1.0.0
dependencies:
  - name: investment
    version: "1.0.0"
    repository: "file://./investment"
    condition: "true"
  - name: postgresql
    version: "1.0.0"
    repository: "file://./postgresql"
    condition: "true"