apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "investment.fullname" . }}-config-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps"]
    verbs: ["get", "list"]
  - apiGroups: ["", "extensions", "apps"]
    resources: ["secrets"]
    verbs: ["get", "list"]
  - apiGroups: [ "", "extensions", "apps" ]
    resources: [ "pods" ]
    verbs: [ "get" ]