apiVersion: v1
kind: Secret
metadata:
  name: {{ include "investment.fullname" . }}-basic-auth
  labels:
    {{- include "investment.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.serviceMonitor.basicAuth.username | b64enc | quote }}
  password: {{ .Values.serviceMonitor.basicAuth.password | b64enc | quote }}