{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "investment.serviceAccountName" . }}
  labels:
    {{- include "investment.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-{{ include "investment.fullname" . }}-config
subjects:
  - kind: ServiceAccount
    name: {{ include "investment.serviceAccountName" . }}
roleRef:
  kind: Role
  name: {{ include "investment.fullname" . }}-config-reader
  apiGroup: rbac.authorization.k8s.io
{{- end }}